### ISSUE TITLE
使用生成pt推理有问题额

### ISSUE THREAD

**Issue by v-yunbin** [tenadolanter/chatTTS-timbre#7]
```
Traceback (most recent call last):
  File "infer_define.py", line 22, in <module>
    wavs = chat.infer(texts, params_infer_code=params_infer_code, use_decoder=True)
  File "/data/disk1/ybZhang/ChatTTS/ChatTTS/core.py", line 140, in infer
    result = infer_code(self.pretrain_models, text, **params_infer_code, return_hidden=use_decoder)
  File "/data/disk1/ybZhang/ChatTTS/ChatTTS/infer/api.py", line 45, in infer_code
    F.normalize(spk_emb.to(device).to(emb.dtype)[None].expand(len(text), -1), p=2.0, dim=1, eps=1e-12)
RuntimeError: expand(torch.cuda.FloatTensor{[1, 1, 40]}, size=[1, -1]): the number of sizes provided (2) must be greater or equal to the number of dimensions in the tensor (3)
```

**Comment by smallkeyonce** [comment]
用chattts加载生成的pt文件，报上面那个错

**Comment by v-yunbin** [comment]
加载的时候发现是三维的，我改成两维的，上面那个错没有了，又报新的错误：
```
Traceback (most recent call last):
  File "infer_define.py", line 27, in <module>
    wavs = chat.infer(texts, params_refine_text=params_refine_text, params_infer_code=params_infer_code, use_decoder=True)
  File "/data/disk1/ybZhang/ChatTTS/ChatTTS/core.py", line 140, in infer
    result = infer_code(self.pretrain_models, text, **params_infer_code, return_hidden=use_decoder)
  File "/data/disk1/ybZhang/ChatTTS/ChatTTS/infer/api.py", line 45, in infer_code
    emb[inputs['input_ids'][..., 0] == models['tokenizer'].convert_tokens_to_ids('[spk_emb]')] = \
RuntimeError: shape mismatch: value tensor of shape [40] cannot be broadcast to indexing result of shape [1, 768]
```

**Comment by lanwanx** [comment]
@tenadolanter   生成存在问题

**Comment by lanwanx** [comment]
@tenadolanter 生成存在问题

**Comment by v-yunbin** [comment]
很奇怪他是怎么跑起来的，#2

**Comment by tenadolanter** [comment]
@v-yunbin    已经修复导致报错的bug

**Comment by v-yunbin** [comment]
> @v-yunbin 已经修复导致报错的bug

好的 我试试

**Comment by v-yunbin** [comment]
@tenadolanter  大佬，我咋还跑不起来？感觉和之前没啥区别
```
Traceback (most recent call last):
  File "infer_define.py", line 27, in <module>
    wavs = chat.infer(texts, params_refine_text=params_refine_text, params_infer_code=params_infer_code, use_decoder=True)
  File "/data/disk1/ybZhang/ChatTTS/ChatTTS/core.py", line 140, in infer
    result = infer_code(self.pretrain_models, text, **params_infer_code, return_hidden=use_decoder)
  File "/data/disk1/ybZhang/ChatTTS/ChatTTS/infer/api.py", line 45, in infer_code
    emb[inputs['input_ids'][..., 0] == models['tokenizer'].convert_tokens_to_ids('[spk_emb]')] = \
RuntimeError: shape mismatch: value tensor of shape [36] cannot be broadcast to indexing result of shape [1, 768]

```

**Comment by tenadolanter** [comment]
https://github.com/jianchang512/ChatTTS-ui/tree/main?tab=readme-ov-file#%E9%9F%B3%E8%89%B2%E8%8E%B7%E5%8F%96

你可以参考一下这个，我使用的之前版本是可以的，最新版我还没试，你先转换一下看看可以用么
